//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicTypeDescriptorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicTypeDescriptorApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus&apos;s day..
        /// </summary>
        internal static string Days_Fri_Desc {
            get {
                return ResourceManager.GetString("Days_Fri_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Days_Fri_Name {
            get {
                return ResourceManager.GetString("Days_Fri_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the Moon..
        /// </summary>
        internal static string Days_Mon_Desc {
            get {
                return ResourceManager.GetString("Days_Mon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Days_Mon_Name {
            get {
                return ResourceManager.GetString("Days_Mon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event will not reoccure..
        /// </summary>
        internal static string Days_None_Desc {
            get {
                return ResourceManager.GetString("Days_None_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        internal static string Days_None_Name {
            get {
                return ResourceManager.GetString("Days_None_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Saturday and Sunday..
        /// </summary>
        internal static string Days_NoWork_Desc {
            get {
                return ResourceManager.GetString("Days_NoWork_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string Days_NoWork_Name {
            get {
                return ResourceManager.GetString("Days_NoWork_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Saturn..
        /// </summary>
        internal static string Days_Sat_Desc {
            get {
                return ResourceManager.GetString("Days_Sat_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Days_Sat_Name {
            get {
                return ResourceManager.GetString("Days_Sat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the sun..
        /// </summary>
        internal static string Days_Sun_Desc {
            get {
                return ResourceManager.GetString("Days_Sun_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Days_Sun_Name {
            get {
                return ResourceManager.GetString("Days_Sun_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Jupiter..
        /// </summary>
        internal static string Days_Thr_Desc {
            get {
                return ResourceManager.GetString("Days_Thr_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Days_Thr_Name {
            get {
                return ResourceManager.GetString("Days_Thr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Mars..
        /// </summary>
        internal static string Days_Tue_Desc {
            get {
                return ResourceManager.GetString("Days_Tue_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Days_Tue_Name {
            get {
                return ResourceManager.GetString("Days_Tue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Mercury..
        /// </summary>
        internal static string Days_Wed_Desc {
            get {
                return ResourceManager.GetString("Days_Wed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Days_Wed_Name {
            get {
                return ResourceManager.GetString("Days_Wed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All days except Saturday and Sunday..
        /// </summary>
        internal static string Days_Work_Desc {
            get {
                return ResourceManager.GetString("Days_Work_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdays.
        /// </summary>
        internal static string Days_Work_Name {
            get {
                return ResourceManager.GetString("Days_Work_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ErrorState1 {
            get {
                object obj = ResourceManager.GetObject("ErrorState1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ErrorState2 {
            get {
                object obj = ResourceManager.GetObject("ErrorState2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HappyFace {
            get {
                object obj = ResourceManager.GetObject("HappyFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OkFace {
            get {
                object obj = ResourceManager.GetObject("OkFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is negative..
        /// </summary>
        internal static string TestClass_Boolean_False_Desc {
            get {
                return ResourceManager.GetString("TestClass_Boolean_False_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nep.
        /// </summary>
        internal static string TestClass_Boolean_False_Name {
            get {
                return ResourceManager.GetString("TestClass_Boolean_False_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is positive..
        /// </summary>
        internal static string TestClass_Boolean_True_Desc {
            get {
                return ResourceManager.GetString("TestClass_Boolean_True_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yep.
        /// </summary>
        internal static string TestClass_Boolean_True_Name {
            get {
                return ResourceManager.GetString("TestClass_Boolean_True_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration features.
        /// </summary>
        internal static string TestClass_Cat1 {
            get {
                return ResourceManager.GetString("TestClass_Cat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General features.
        /// </summary>
        internal static string TestClass_Cat2 {
            get {
                return ResourceManager.GetString("TestClass_Cat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image features.
        /// </summary>
        internal static string TestClass_Cat3 {
            get {
                return ResourceManager.GetString("TestClass_Cat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard values usage.
        /// </summary>
        internal static string TestClass_Cat4 {
            get {
                return ResourceManager.GetString("TestClass_Cat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable IEnumerable.
        /// </summary>
        internal static string TestClass_Cat5 {
            get {
                return ResourceManager.GetString("TestClass_Cat5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is centered on the current display, and has the dimensions specified in the form&apos;s size..
        /// </summary>
        internal static string TestClass_FormStartPosition_CenterParent_Desc {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_CenterParent_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Parent.
        /// </summary>
        internal static string TestClass_FormStartPosition_CenterParent_Name {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_CenterParent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is positioned at the Windows default location and has the dimensions specified in the form&apos;s size..
        /// </summary>
        internal static string TestClass_FormStartPosition_CenterScreen_Desc {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_CenterScreen_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Screen.
        /// </summary>
        internal static string TestClass_FormStartPosition_CenterScreen_Name {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_CenterScreen_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position of the form is determined by the Location property..
        /// </summary>
        internal static string TestClass_FormStartPosition_Manual_Desc {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_Manual_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string TestClass_FormStartPosition_Manual_Name {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_Manual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is positioned at the Windows default location and has the bounds determined by Windows default..
        /// </summary>
        internal static string TestClass_FormStartPosition_WindowsDefaultBounds_Desc {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_WindowsDefaultBounds_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default Bound.
        /// </summary>
        internal static string TestClass_FormStartPosition_WindowsDefaultBounds_Name {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_WindowsDefaultBounds_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is centered within the bounds of its parent form.
        /// </summary>
        internal static string TestClass_FormStartPosition_WindowsDefaultLocation_Desc {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_WindowsDefaultLocation_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Default Location.
        /// </summary>
        internal static string TestClass_FormStartPosition_WindowsDefaultLocation_Name {
            get {
                return ResourceManager.GetString("TestClass_FormStartPosition_WindowsDefaultLocation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use enumeration without FlagsAttribute..
        /// </summary>
        internal static string TestClass_PropA_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropA_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum without Flags.
        /// </summary>
        internal static string TestClass_PropA_Name {
            get {
                return ResourceManager.GetString("TestClass_PropA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use enumeration with FlagsAttribute..
        /// </summary>
        internal static string TestClass_PropB_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropB_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum with Flags.
        /// </summary>
        internal static string TestClass_PropB_Name {
            get {
                return ResourceManager.GetString("TestClass_PropB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use booean as enumeration..
        /// </summary>
        internal static string TestClass_PropC_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropC_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows &apos;No&apos; instead of &apos;False&apos;..
        /// </summary>
        internal static string TestClass_PropC_False_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropC_False_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TestClass_PropC_False_Name {
            get {
                return ResourceManager.GetString("TestClass_PropC_False_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean without True/False.
        /// </summary>
        internal static string TestClass_PropC_Name {
            get {
                return ResourceManager.GetString("TestClass_PropC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows &apos;Yes&apos; instead of &apos;True&apos;..
        /// </summary>
        internal static string TestClass_PropC_True_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropC_True_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TestClass_PropC_True_Name {
            get {
                return ResourceManager.GetString("TestClass_PropC_True_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use built-in enumeration..
        /// </summary>
        internal static string TestClass_PropD_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropD_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in enumeration.
        /// </summary>
        internal static string TestClass_PropD_Name {
            get {
                return ResourceManager.GetString("TestClass_PropD_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property was created at run-time..
        /// </summary>
        internal static string TestClass_PropE_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropE_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-the-fly property.
        /// </summary>
        internal static string TestClass_PropE_Name {
            get {
                return ResourceManager.GetString("TestClass_PropE_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate how to disable a property..
        /// </summary>
        internal static string TestClass_PropF_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropF_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled property.
        /// </summary>
        internal static string TestClass_PropF_Name {
            get {
                return ResourceManager.GetString("TestClass_PropF_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows image for the property value. Test values:  0, 1, 2, and 3..
        /// </summary>
        internal static string TestClass_PropG_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropG_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value image.
        /// </summary>
        internal static string TestClass_PropG_Name {
            get {
                return ResourceManager.GetString("TestClass_PropG_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how you can show an state image for your property. Test values:  0, 1, 2, and 3..
        /// </summary>
        internal static string TestClass_PropH_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropH_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State image(s).
        /// </summary>
        internal static string TestClass_PropH_Name {
            get {
                return ResourceManager.GetString("TestClass_PropH_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate the use of standard values.  This list is not exclusive, meaning you can type in the field.  Test values:  adam, brian, russel, jones, jakob, 101, 102, 103, 104, 105 and any integer value..
        /// </summary>
        internal static string TestClass_PropI_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropI_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard value non-excluive.
        /// </summary>
        internal static string TestClass_PropI_Name {
            get {
                return ResourceManager.GetString("TestClass_PropI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate the use of standard values.  This list is exclusive, meaning you can not type in the field. .
        /// </summary>
        internal static string TestClass_PropJ_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropJ_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard value excluive.
        /// </summary>
        internal static string TestClass_PropJ_Name {
            get {
                return ResourceManager.GetString("TestClass_PropJ_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate the use of expandable list..
        /// </summary>
        internal static string TestClass_PropK_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropK_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable list.
        /// </summary>
        internal static string TestClass_PropK_Name {
            get {
                return ResourceManager.GetString("TestClass_PropK_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate the use of expandable array..
        /// </summary>
        internal static string TestClass_PropL_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropL_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable array.
        /// </summary>
        internal static string TestClass_PropL_Name {
            get {
                return ResourceManager.GetString("TestClass_PropL_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate the use of expandable collection..
        /// </summary>
        internal static string TestClass_PropM_Desc {
            get {
                return ResourceManager.GetString("TestClass_PropM_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandable collection.
        /// </summary>
        internal static string TestClass_PropM_Name {
            get {
                return ResourceManager.GetString("TestClass_PropM_Name", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap UnhappyFace {
            get {
                object obj = ResourceManager.GetObject("UnhappyFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
