'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
'
Namespace LOG_DM_Department_BasicWS__c
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PortSoapBinding", [Namespace]:="urn:LOG_DM_Department_BasicWS__c")>  _
    Partial Public Class LOG_DM_Department_BasicWS__cService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private authenticationInfoValueField As AuthenticationInfo
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ServiceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            '  Me.Url = Global.ADAdminDotNet.My.MySettings.Default.ADAdminConsole_LOG_DM_Department_BasicWS__c_LOG_DM_Department_BasicWS__cService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property AuthenticationInfoValue() As AuthenticationInfo
            Get
                Return Me.authenticationInfoValueField
            End Get
            Set
                Me.authenticationInfoValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCompleted As GetCompletedEventHandler
        
        '''<remarks/>
        Public Event SetCompleted As SetCompletedEventHandler
        
        '''<remarks/>
        Public Event ServiceCompleted As ServiceCompletedEventHandler
        
        '''<remarks/>
        Public Event GetListCompleted As GetListCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:LOG_DM_Department_BasicWS__c/Create", RequestNamespace:="urn:LOG_DM_Department_BasicWS__c", ResponseNamespace:="urn:LOG_DM_Department_BasicWS__c", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Create( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As StatusType,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    <System.ComponentModel.DefaultValueAttribute(1)> ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-FMS")> ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-EFT")> ByVal PreEFT As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-PER")> ByVal PrePER As String) As <System.Xml.Serialization.XmlElementAttribute("Dept_ID")> String
            Dim results() As Object = Me.Invoke("Create", New Object() {Submitter, Department_Type, Status, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As StatusType,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String)
            Me.CreateAsync(Submitter, Department_Type, Status, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As StatusType,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String,  _
                    ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {Submitter, Department_Type, Status, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:LOG_DM_Department_BasicWS__c/Get", RequestNamespace:="urn:LOG_DM_Department_BasicWS__c", ResponseNamespace:="urn:LOG_DM_Department_BasicWS__c", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function [Get]( _
                    ByRef Dept_ID As String,  _
                    ByRef Create_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Create_DateSpecified As Boolean,  _
                    ByRef Department_Type As String,  _
                    ByRef Last_Modified_By As String,  _
                    ByRef Modified_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Modified_DateSpecified As Boolean,  _
                    ByRef Status As StatusType,  _
                    ByRef Department_Name As String,  _
                    ByRef Status_History As String,  _
                    ByRef Postal_Address As String,  _
                    ByRef Store_Number As String,  _
                    ByRef City As String,  _
                    ByRef Province As String,  _
                    ByRef Postal_Code As String,  _
                    ByRef zDispCheckDuplicate As String,  _
                    ByRef zDispOldStoreNumber As String,  _
                    ByRef System_Group As String,  _
                    ByRef zDispIntStoreNo As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef zDispIntStoreNoSpecified As Boolean,  _
                    ByRef Billing_Code As String,  _
                    <System.ComponentModel.DefaultValueAttribute(1)> ByRef Data_Fix_Counter As Integer,  _
                    ByRef Region As String,  _
                    ByRef Implementation_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Implementation_DateSpecified As Boolean,  _
                    ByRef Database As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-FMS")> ByRef PreFMS As String,  _
                    ByRef User_Code As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-EFT")> ByRef PreEFT As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-PER")> ByRef PrePER As String) As <System.Xml.Serialization.XmlElementAttribute("Submitter")> String
            Dim results() As Object = Me.Invoke("Get", New Object() {Dept_ID})
            Dept_ID = CType(results(1),String)
            Create_Date = CType(results(2),Date)
            Create_DateSpecified = CType(results(3),Boolean)
            Department_Type = CType(results(4),String)
            Last_Modified_By = CType(results(5),String)
            Modified_Date = CType(results(6),Date)
            Modified_DateSpecified = CType(results(7),Boolean)
            Status = CType(results(8),StatusType)
            Department_Name = CType(results(9),String)
            Status_History = CType(results(10),String)
            Postal_Address = CType(results(11),String)
            Store_Number = CType(results(12),String)
            City = CType(results(13),String)
            Province = CType(results(14),String)
            Postal_Code = CType(results(15),String)
            zDispCheckDuplicate = CType(results(16),String)
            zDispOldStoreNumber = CType(results(17),String)
            System_Group = CType(results(18),String)
            zDispIntStoreNo = CType(results(19),Integer)
            zDispIntStoreNoSpecified = CType(results(20),Boolean)
            Billing_Code = CType(results(21),String)
            Data_Fix_Counter = CType(results(22),Integer)
            Region = CType(results(23),String)
            Implementation_Date = CType(results(24),Date)
            Implementation_DateSpecified = CType(results(25),Boolean)
            Database = CType(results(26),String)
            PreFMS = CType(results(27),String)
            User_Code = CType(results(28),String)
            PreEFT = CType(results(29),String)
            PrePER = CType(results(30),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAsync(ByVal Dept_ID As String)
            Me.GetAsync(Dept_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAsync(ByVal Dept_ID As String, ByVal userState As Object)
            If (Me.GetOperationCompleted Is Nothing) Then
                Me.GetOperationCompleted = AddressOf Me.OnGetOperationCompleted
            End If
            Me.InvokeAsync("Get", New Object() {Dept_ID}, Me.GetOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCompleted(Me, New GetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:LOG_DM_Department_BasicWS__c/Set", RequestNamespace:="urn:LOG_DM_Department_BasicWS__c", ResponseNamespace:="urn:LOG_DM_Department_BasicWS__c", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub [Set]( _
                    <System.ComponentModel.DefaultValueAttribute("$USER$")> ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal Status As System.Nullable(Of StatusType),  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByVal StatusSpecified As Boolean,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    <System.ComponentModel.DefaultValueAttribute(1)> ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-FMS")> ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-EFT")> ByVal PreEFT As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-PER")> ByVal PrePER As String,  _
                    ByRef Dept_ID As String)
            Dim results() As Object = Me.Invoke("Set", New Object() {Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER, Dept_ID})
            Dept_ID = CType(results(0),String)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As System.Nullable(Of StatusType),  _
                    ByVal StatusSpecified As Boolean,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String,  _
                    ByVal Dept_ID As String)
            Me.SetAsync(Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER, Dept_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As System.Nullable(Of StatusType),  _
                    ByVal StatusSpecified As Boolean,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String,  _
                    ByVal Dept_ID As String,  _
                    ByVal userState As Object)
            If (Me.SetOperationCompleted Is Nothing) Then
                Me.SetOperationCompleted = AddressOf Me.OnSetOperationCompleted
            End If
            Me.InvokeAsync("Set", New Object() {Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER, Dept_ID}, Me.SetOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetCompleted(Me, New SetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:LOG_DM_Department_BasicWS__c/Service", RequestNamespace:="urn:LOG_DM_Department_BasicWS__c", ResponseNamespace:="urn:LOG_DM_Department_BasicWS__c", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Service( _
                    <System.ComponentModel.DefaultValueAttribute("$USER$")> ByRef Submitter As String,  _
                    ByRef Department_Type As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByRef Status As System.Nullable(Of StatusType),  _
                    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true), System.Xml.Serialization.XmlIgnoreAttribute()> ByRef StatusSpecified As Boolean,  _
                    ByRef Department_Name As String,  _
                    ByRef Postal_Address As String,  _
                    ByRef Store_Number As String,  _
                    ByRef City As String,  _
                    ByRef Province As String,  _
                    ByRef Postal_Code As String,  _
                    ByRef zDispCheckDuplicate As String,  _
                    ByRef zDispOldStoreNumber As String,  _
                    ByRef System_Group As String,  _
                    ByRef zDispIntStoreNo As Integer,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef zDispIntStoreNoSpecified As Boolean,  _
                    ByRef Billing_Code As String,  _
                    <System.ComponentModel.DefaultValueAttribute(1)> ByRef Data_Fix_Counter As Integer,  _
                    ByRef Region As String,  _
                    ByRef Implementation_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Implementation_DateSpecified As Boolean,  _
                    ByRef Database As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-FMS")> ByRef PreFMS As String,  _
                    ByRef User_Code As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-EFT")> ByRef PreEFT As String,  _
                    <System.Xml.Serialization.XmlElementAttribute("Pre-PER")> ByRef PrePER As String,  _
                    ByRef Create_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Create_DateSpecified As Boolean,  _
                    ByRef Last_Modified_By As String,  _
                    ByRef Modified_Date As Date,  _
                    <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef Modified_DateSpecified As Boolean,  _
                    ByRef Status_History As String) As <System.Xml.Serialization.XmlElementAttribute("Dept_ID")> String
            Dim results() As Object = Me.Invoke("Service", New Object() {Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER})
            Submitter = CType(results(1),String)
            Department_Type = CType(results(2),String)
            Status = CType(results(3),System.Nullable(Of StatusType))
            StatusSpecified = CType(results(4),Boolean)
            Department_Name = CType(results(5),String)
            Postal_Address = CType(results(6),String)
            Store_Number = CType(results(7),String)
            City = CType(results(8),String)
            Province = CType(results(9),String)
            Postal_Code = CType(results(10),String)
            zDispCheckDuplicate = CType(results(11),String)
            zDispOldStoreNumber = CType(results(12),String)
            System_Group = CType(results(13),String)
            zDispIntStoreNo = CType(results(14),Integer)
            zDispIntStoreNoSpecified = CType(results(15),Boolean)
            Billing_Code = CType(results(16),String)
            Data_Fix_Counter = CType(results(17),Integer)
            Region = CType(results(18),String)
            Implementation_Date = CType(results(19),Date)
            Implementation_DateSpecified = CType(results(20),Boolean)
            Database = CType(results(21),String)
            PreFMS = CType(results(22),String)
            User_Code = CType(results(23),String)
            PreEFT = CType(results(24),String)
            PrePER = CType(results(25),String)
            Create_Date = CType(results(26),Date)
            Create_DateSpecified = CType(results(27),Boolean)
            Last_Modified_By = CType(results(28),String)
            Modified_Date = CType(results(29),Date)
            Modified_DateSpecified = CType(results(30),Boolean)
            Status_History = CType(results(31),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ServiceAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As System.Nullable(Of StatusType),  _
                    ByVal StatusSpecified As Boolean,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String)
            Me.ServiceAsync(Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ServiceAsync( _
                    ByVal Submitter As String,  _
                    ByVal Department_Type As String,  _
                    ByVal Status As System.Nullable(Of StatusType),  _
                    ByVal StatusSpecified As Boolean,  _
                    ByVal Department_Name As String,  _
                    ByVal Postal_Address As String,  _
                    ByVal Store_Number As String,  _
                    ByVal City As String,  _
                    ByVal Province As String,  _
                    ByVal Postal_Code As String,  _
                    ByVal zDispCheckDuplicate As String,  _
                    ByVal zDispOldStoreNumber As String,  _
                    ByVal System_Group As String,  _
                    ByVal zDispIntStoreNo As Integer,  _
                    ByVal zDispIntStoreNoSpecified As Boolean,  _
                    ByVal Billing_Code As String,  _
                    ByVal Data_Fix_Counter As Integer,  _
                    ByVal Region As String,  _
                    ByVal Implementation_Date As Date,  _
                    ByVal Implementation_DateSpecified As Boolean,  _
                    ByVal Database As String,  _
                    ByVal PreFMS As String,  _
                    ByVal User_Code As String,  _
                    ByVal PreEFT As String,  _
                    ByVal PrePER As String,  _
                    ByVal userState As Object)
            If (Me.ServiceOperationCompleted Is Nothing) Then
                Me.ServiceOperationCompleted = AddressOf Me.OnServiceOperationCompleted
            End If
            Me.InvokeAsync("Service", New Object() {Submitter, Department_Type, Status, StatusSpecified, Department_Name, Postal_Address, Store_Number, City, Province, Postal_Code, zDispCheckDuplicate, zDispOldStoreNumber, System_Group, zDispIntStoreNo, zDispIntStoreNoSpecified, Billing_Code, Data_Fix_Counter, Region, Implementation_Date, Implementation_DateSpecified, Database, PreFMS, User_Code, PreEFT, PrePER}, Me.ServiceOperationCompleted, userState)
        End Sub
        
        Private Sub OnServiceOperationCompleted(ByVal arg As Object)
            If (Not (Me.ServiceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ServiceCompleted(Me, New ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationInfoValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:LOG_DM_Department_BasicWS__c/GetList", RequestNamespace:="urn:LOG_DM_Department_BasicWS__c", ResponseNamespace:="urn:LOG_DM_Department_BasicWS__c", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetList(ByVal Qualification As String, ByVal startRecord As String, ByVal maxLimit As String) As <System.Xml.Serialization.XmlElementAttribute("getListValues")> OutputMapping5GetListValues()
            Dim results() As Object = Me.Invoke("GetList", New Object() {Qualification, startRecord, maxLimit})
            Return CType(results(0),OutputMapping5GetListValues())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetListAsync(ByVal Qualification As String, ByVal startRecord As String, ByVal maxLimit As String)
            Me.GetListAsync(Qualification, startRecord, maxLimit, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetListAsync(ByVal Qualification As String, ByVal startRecord As String, ByVal maxLimit As String, ByVal userState As Object)
            If (Me.GetListOperationCompleted Is Nothing) Then
                Me.GetListOperationCompleted = AddressOf Me.OnGetListOperationCompleted
            End If
            Me.InvokeAsync("GetList", New Object() {Qualification, startRecord, maxLimit}, Me.GetListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetListCompleted(Me, New GetListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:LOG_DM_Department_BasicWS__c"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="urn:LOG_DM_Department_BasicWS__c", IsNullable:=false)>  _
    Partial Public Class AuthenticationInfo
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private authenticationField As String
        
        Private localeField As String
        
        Private timeZoneField As String
        
        '''<remarks/>
        Public Property userName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property authentication() As String
            Get
                Return Me.authenticationField
            End Get
            Set
                Me.authenticationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property locale() As String
            Get
                Return Me.localeField
            End Get
            Set
                Me.localeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property timeZone() As String
            Get
                Return Me.timeZoneField
            End Get
            Set
                Me.timeZoneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:LOG_DM_Department_BasicWS__c")>  _
    Public Enum StatusType
        
        '''<remarks/>
        Active
        
        '''<remarks/>
        Inactive
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:LOG_DM_Department_BasicWS__c")>  _
    Partial Public Class OutputMapping5GetListValues
        
        Private dept_IDField As String
        
        Private submitterField As String
        
        Private create_DateField As Date
        
        Private create_DateFieldSpecified As Boolean
        
        Private department_TypeField As String
        
        Private last_Modified_ByField As String
        
        Private modified_DateField As Date
        
        Private modified_DateFieldSpecified As Boolean
        
        Private statusField As StatusType
        
        Private department_NameField As String
        
        Private status_HistoryField As String
        
        Private postal_AddressField As String
        
        Private store_NumberField As String
        
        Private cityField As String
        
        Private provinceField As String
        
        Private postal_CodeField As String
        
        Private zDispCheckDuplicateField As String
        
        Private zDispOldStoreNumberField As String
        
        Private system_GroupField As String
        
        Private zDispIntStoreNoField As Integer
        
        Private zDispIntStoreNoFieldSpecified As Boolean
        
        Private billing_CodeField As String
        
        Private data_Fix_CounterField As Integer
        
        Private regionField As String
        
        Private implementation_DateField As Date
        
        Private implementation_DateFieldSpecified As Boolean
        
        Private databaseField As String
        
        Private preFMSField As String
        
        Private user_CodeField As String
        
        Private preEFTField As String
        
        Private prePERField As String
        
        Public Sub New()
            MyBase.New
            Me.data_Fix_CounterField = 1
        End Sub
        
        '''<remarks/>
        Public Property Dept_ID() As String
            Get
                Return Me.dept_IDField
            End Get
            Set
                Me.dept_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Submitter() As String
            Get
                Return Me.submitterField
            End Get
            Set
                Me.submitterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Create_Date() As Date
            Get
                Return Me.create_DateField
            End Get
            Set
                Me.create_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Create_DateSpecified() As Boolean
            Get
                Return Me.create_DateFieldSpecified
            End Get
            Set
                Me.create_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department_Type() As String
            Get
                Return Me.department_TypeField
            End Get
            Set
                Me.department_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Last_Modified_By() As String
            Get
                Return Me.last_Modified_ByField
            End Get
            Set
                Me.last_Modified_ByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Modified_Date() As Date
            Get
                Return Me.modified_DateField
            End Get
            Set
                Me.modified_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Modified_DateSpecified() As Boolean
            Get
                Return Me.modified_DateFieldSpecified
            End Get
            Set
                Me.modified_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As StatusType
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department_Name() As String
            Get
                Return Me.department_NameField
            End Get
            Set
                Me.department_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status_History() As String
            Get
                Return Me.status_HistoryField
            End Get
            Set
                Me.status_HistoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Postal_Address() As String
            Get
                Return Me.postal_AddressField
            End Get
            Set
                Me.postal_AddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Store_Number() As String
            Get
                Return Me.store_NumberField
            End Get
            Set
                Me.store_NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Province() As String
            Get
                Return Me.provinceField
            End Get
            Set
                Me.provinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Postal_Code() As String
            Get
                Return Me.postal_CodeField
            End Get
            Set
                Me.postal_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zDispCheckDuplicate() As String
            Get
                Return Me.zDispCheckDuplicateField
            End Get
            Set
                Me.zDispCheckDuplicateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zDispOldStoreNumber() As String
            Get
                Return Me.zDispOldStoreNumberField
            End Get
            Set
                Me.zDispOldStoreNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property System_Group() As String
            Get
                Return Me.system_GroupField
            End Get
            Set
                Me.system_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property zDispIntStoreNo() As Integer
            Get
                Return Me.zDispIntStoreNoField
            End Get
            Set
                Me.zDispIntStoreNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zDispIntStoreNoSpecified() As Boolean
            Get
                Return Me.zDispIntStoreNoFieldSpecified
            End Get
            Set
                Me.zDispIntStoreNoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Billing_Code() As String
            Get
                Return Me.billing_CodeField
            End Get
            Set
                Me.billing_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(1)>  _
        Public Property Data_Fix_Counter() As Integer
            Get
                Return Me.data_Fix_CounterField
            End Get
            Set
                Me.data_Fix_CounterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Region() As String
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Implementation_Date() As Date
            Get
                Return Me.implementation_DateField
            End Get
            Set
                Me.implementation_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Implementation_DateSpecified() As Boolean
            Get
                Return Me.implementation_DateFieldSpecified
            End Get
            Set
                Me.implementation_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Database() As String
            Get
                Return Me.databaseField
            End Get
            Set
                Me.databaseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Pre-FMS")>  _
        Public Property PreFMS() As String
            Get
                Return Me.preFMSField
            End Get
            Set
                Me.preFMSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_Code() As String
            Get
                Return Me.user_CodeField
            End Get
            Set
                Me.user_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Pre-EFT")>  _
        Public Property PreEFT() As String
            Get
                Return Me.preEFTField
            End Get
            Set
                Me.preEFTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Pre-PER")>  _
        Public Property PrePER() As String
            Get
                Return Me.prePERField
            End Get
            Set
                Me.prePERField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetCompletedEventHandler(ByVal sender As Object, ByVal e As GetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Dept_ID() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Create_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Create_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Department_Type() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Last_Modified_By() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Modified_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(6),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Modified_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(7),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Status() As StatusType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(8),StatusType)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Department_Name() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(9),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Status_History() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(10),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Postal_Address() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(11),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Store_Number() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(12),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property City() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(13),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Province() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(14),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Postal_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(15),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispCheckDuplicate() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(16),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispOldStoreNumber() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(17),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property System_Group() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(18),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispIntStoreNo() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(19),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispIntStoreNoSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(20),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Billing_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(21),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Data_Fix_Counter() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(22),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Region() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(23),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Implementation_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(24),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Implementation_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(25),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Database() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(26),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PreFMS() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(27),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property User_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(28),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PreEFT() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(29),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PrePER() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(30),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub SetCompletedEventHandler(ByVal sender As Object, ByVal e As SetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Dept_ID() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub ServiceCompletedEventHandler(ByVal sender As Object, ByVal e As ServiceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ServiceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Submitter() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Department_Type() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Status() As System.Nullable(Of StatusType)
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),System.Nullable(Of StatusType))
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property StatusSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Department_Name() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Postal_Address() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(6),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Store_Number() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(7),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property City() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(8),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Province() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(9),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Postal_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(10),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispCheckDuplicate() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(11),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispOldStoreNumber() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(12),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property System_Group() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(13),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispIntStoreNo() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(14),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property zDispIntStoreNoSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(15),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Billing_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(16),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Data_Fix_Counter() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(17),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Region() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(18),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Implementation_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(19),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Implementation_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(20),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Database() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(21),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PreFMS() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(22),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property User_Code() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(23),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PreEFT() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(24),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property PrePER() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(25),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Create_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(26),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Create_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(27),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Last_Modified_By() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(28),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Modified_Date() As Date
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(29),Date)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Modified_DateSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(30),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Status_History() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(31),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetListCompletedEventHandler(ByVal sender As Object, ByVal e As GetListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OutputMapping5GetListValues()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OutputMapping5GetListValues())
            End Get
        End Property
    End Class
End Namespace
