'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits Global.System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = DirectCast(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property BanList() As String
			Get
				Return DirectCast(Me("BanList"), String)
			End Get
			Set
				Me("BanList") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public Property AcceptList() As String
			Get
				Return DirectCast(Me("AcceptList"), String)
			End Get
			Set
				Me("AcceptList") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("21")> _
		Public Property ServerPort() As Decimal
			Get
				Return CDec(Me("ServerPort"))
			End Get
			Set
				Me("ServerPort") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("120")> _
		Public Property DownloadSpeed() As Decimal
			Get
				Return CDec(Me("DownloadSpeed"))
			End Get
			Set
				Me("DownloadSpeed") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("120")> _
		Public Property UploadSpeed() As Decimal
			Get
				Return CDec(Me("UploadSpeed"))
			End Get
			Set
				Me("UploadSpeed") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property DlLimit() As Boolean
			Get
				Return CBool(Me("DlLimit"))
			End Get
			Set
				Me("DlLimit") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("False")> _
		Public Property Ullimit() As Boolean
			Get
				Return CBool(Me("Ullimit"))
			End Get
			Set
				Me("Ullimit") = value
			End Set
		End Property

		<System.Configuration.UserScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("0, 0")> _
		Public Property WindowPosition() As Global.System.Drawing.Point
			Get
				Return CType(Me("WindowPosition"), Global.System.Drawing.Point)
			End Get
			Set
				Me("WindowPosition") = value
			End Set
		End Property
	End Class
End Namespace
