''------------------------------------------------------------------------------
'' <auto-generated>
''     This code was generated by a tool.
''     Runtime Version:4.0.30319.42000
''
''     Changes to this file may cause incorrect behavior and will be lost if
''     the code is regenerated.
'' </auto-generated>
''------------------------------------------------------------------------------

'Option Strict On
'Option Explicit On


'Namespace My

'    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
'     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
'     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
'    Partial Friend NotInheritable Class MySettings
'        Inherits Global.System.Configuration.ApplicationSettingsBase

'        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

'#Region "My.Settings Auto-Save Functionality"
'#If _MyType = "WindowsForms" Then
'        Private Shared addedHandler As Boolean

'        Private Shared addedHandlerLockObject As New Object

'        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
'        Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
'            If My.Application.SaveMySettingsOnExit Then
'                My.Settings.Save()
'            End If
'        End Sub
'#End If
'#End Region

'        Public Shared ReadOnly Property [Default]() As MySettings
'            Get

'#If _MyType = "WindowsForms" Then
'                If Not addedHandler Then
'                    SyncLock addedHandlerLockObject
'                        If Not addedHandler Then
'                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
'                            addedHandler = True
'                        End If
'                    End SyncLock
'                End If
'#End If
'                Return defaultInstance
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("10.123.45.180")> _
'        Public Property IP_ADDRESS_PRD() As String
'            Get
'                Return CType(Me("IP_ADDRESS_PRD"), String)
'            End Get
'            Set(value As String)
'                Me("IP_ADDRESS_PRD") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("10.123.45.210")> _
'        Public Property IP_ADDRESS_QA() As String
'            Get
'                Return CType(Me("IP_ADDRESS_QA"), String)
'            End Get
'            Set(value As String)
'                Me("IP_ADDRESS_QA") = value
'            End Set
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=USERS,OU=Vulindlela3,DC=vulindlelaprd,DC=gov,DC=za")> _
'        Public ReadOnly Property AD_USERS_PRD() As String
'            Get
'                Return CType(Me("AD_USERS_PRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=USERS,OU=Vulindlela3,DC=vulqa,DC=pwv,DC=gov,DC=za")> _
'        Public ReadOnly Property AD_USERS_QA() As String
'            Get
'                Return CType(Me("AD_USERS_QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("DC=vulprd,DC=pwv,DC=gov,DC=za")> _
'        Public ReadOnly Property AD_DC_PRD() As String
'            Get
'                Return CType(Me("AD_DC_PRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("DC=vulqa,DC=pwv,DC=gov,DC=za")> _
'        Public ReadOnly Property AD_DC_QA() As String
'            Get
'                Return CType(Me("AD_DC_QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("VULWEB")> _
'        Public ReadOnly Property AD_ServerName_PRD() As String
'            Get
'                Return CType(Me("AD_ServerName_PRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("VULQA1")> _
'        Public ReadOnly Property AD_ServerName_QA() As String
'            Get
'                Return CType(Me("AD_ServerName_QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("vulsystem")> _
'        Public ReadOnly Property ADSMasterUsername_PRD() As String
'            Get
'                Return CType(Me("ADSMasterUsername_PRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("vulsystem")> _
'        Public ReadOnly Property ADSMasterUsername_QA() As String
'            Get
'                Return CType(Me("ADSMasterUsername_QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
'        Public ReadOnly Property Active_QA() As Boolean
'            Get
'                Return CType(Me("Active_QA"), Boolean)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
'        Public ReadOnly Property Active_PRD() As Boolean
'            Get
'                Return CType(Me("Active_PRD"), Boolean)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("UnRlqHdCaqp8mOHvR2N3bg==")> _
'        Public ReadOnly Property ADSMasterPassword_PRD() As String
'            Get
'                Return CType(Me("ADSMasterPassword_PRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("UnRlqHdCaqp8mOHvR2N3bg==")> _
'        Public ReadOnly Property ADSMasterPassword_QA() As String
'            Get
'                Return CType(Me("ADSMasterPassword_QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://10.123.45.210/")> _
'        Public Property WEBURLQA() As String
'            Get
'                Return CType(Me("WEBURLQA"), String)
'            End Get
'            Set(value As String)
'                Me("WEBURLQA") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://www.vulindlela.gov.za/")> _
'        Public Property WEBURLPRD() As String
'            Get
'                Return CType(Me("WEBURLPRD"), String)
'            End Get
'            Set(value As String)
'                Me("WEBURLPRD") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("False")> _
'        Public Property ValidUser() As Boolean
'            Get
'                Return CType(Me("ValidUser"), Boolean)
'            End Get
'            Set(value As Boolean)
'                Me("ValidUser") = value
'            End Set
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=APPLICATION_RIGHTS,OU=Vulindlela3,DC=vulindlelaprd,DC=gov,DC=za")> _
'        Public ReadOnly Property contextApplicationPRD() As String
'            Get
'                Return CType(Me("contextApplicationPRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=APPLICATION_RIGHTS,OU=Vulindlela3,DC=vulqa,DC=pwv,DC=gov,DC=za")> _
'        Public ReadOnly Property contextApplicationQA() As String
'            Get
'                Return CType(Me("contextApplicationQA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=Vulindlela3,DC=vulindlelaprd,DC=gov,DC=za")> _
'        Public ReadOnly Property VulindlelaContextPRD() As String
'            Get
'                Return CType(Me("VulindlelaContextPRD"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("OU=Vulindlela3,DC=vulqa,DC=pwv,DC=gov,DC=za")> _
'        Public ReadOnly Property VulindlelaContextQA() As String
'            Get
'                Return CType(Me("VulindlelaContextQA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("(012 - 657 4444)")> _
'        Public Property HelpDesk_PhoneNo() As String
'            Get
'                Return CType(Me("HelpDesk_PhoneNo"), String)
'            End Get
'            Set(value As String)
'                Me("HelpDesk_PhoneNo") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("10.123.45.210")> _
'        Public Property SMTPServerIPAddress() As String
'            Get
'                Return CType(Me("SMTPServerIPAddress"), String)
'            End Get
'            Set(value As String)
'                Me("SMTPServerIPAddress") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("prodlgremv1")> _
'        Public Property RemedyServerName() As String
'            Get
'                Return CType(Me("RemedyServerName"), String)
'            End Get
'            Set(value As String)
'                Me("RemedyServerName") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("T0005221" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10))> _
'        Public Property RemedyUserName() As String
'            Get
'                Return CType(Me("RemedyUserName"), String)
'            End Get
'            Set(value As String)
'                Me("RemedyUserName") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("WCP,Ralton Kirby <Rkirby@pgwc.gov.za>|NCP,Michael Femmers <femmersm@ncpg.gov.za>")> _
'        Public Property Vulindlela_Controllers() As String
'            Get
'                Return CType(Me("Vulindlela_Controllers"), String)
'            End Get
'            Set(value As String)
'                Me("Vulindlela_Controllers") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("prodlgremv1")> _
'        Public Property ARSServerName() As String
'            Get
'                Return CType(Me("ARSServerName"), String)
'            End Get
'            Set(value As String)
'                Me("ARSServerName") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("80")> _
'        Public Property ARServerPort() As String
'            Get
'                Return CType(Me("ARServerPort"), String)
'            End Get
'            Set(value As String)
'                Me("ARServerPort") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("T0005221")> _
'        Public Property ARUser() As String
'            Get
'                Return CType(Me("ARUser"), String)
'            End Get
'            Set(value As String)
'                Me("ARUser") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("logik007")> _
'        Public Property ARPassword() As String
'            Get
'                Return CType(Me("ARPassword"), String)
'            End Get
'            Set(value As String)
'                Me("ARPassword") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("mpu_|Mpumalanga,kzn_|Kwazulu Natal,nop_|Limpopo,gau_|Gauteng,wcp_|Western Cape,ec" & _
'            "p_|Eastern Cape,nwp_|North West,fsp_|Free State")> _
'        Public Property DeptDescPair() As String
'            Get
'                Return CType(Me("DeptDescPair"), String)
'            End Get
'            Set(value As String)
'                Me("DeptDescPair") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\vul2126\AppData\Local\Google\Chrome\Application\chrome.exe")> _
'        Public Property WebBrowserEXE() As String
'            Get
'                Return CType(Me("WebBrowserEXE"), String)
'            End Get
'            Set(value As String)
'                Me("WebBrowserEXE") = value
'            End Set
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=prodlgsqlv1.logis.gov.za\SQL2012;Initial Catalog=ARSystem;Integrated " & _
'            "Security=True;Connect Timeout=120")> _
'        Public ReadOnly Property ARSystemConnectionString() As String
'            Get
'                Return CType(Me("ARSystemConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.180;Initial Catalog=ADS;User ID=sa;Password=M33Q1Serv!ce09;" & _
'            "Connect Timeout=120")> _
'        Public ReadOnly Property AdsPRDConnectionString() As String
'            Get
'                Return CType(Me("AdsPRDConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.180;Initial Catalog=ADS;User ID=sa;Password=M33Q1Serv!ce09;" & _
'            "Connect Timeout=120")> _
'        Public ReadOnly Property AdsConnectionString() As String
'            Get
'                Return CType(Me("AdsConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute(" Data Source=10.123.45.180;Initial Catalog=VIP_EXPANDED;User ID=sa;Password=M33Q1" & _
'            "Serv!ce09;Connect Timeout=120")> _
'        Public ReadOnly Property VIP_EXPANDEDConnectionString() As String
'            Get
'                Return CType(Me("VIP_EXPANDEDConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://prodlgremv1/arsys/services/ARService?server=ProdLGRemV1&webService=WS_CI__" & _
'            "c1")> _
'        Public ReadOnly Property ADAdminConsole_WS_CI__c1_WS_CI__c1Service() As String
'            Get
'                Return CType(Me("ADAdminConsole_WS_CI__c1_WS_CI__c1Service"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://prodlgremv1/arsys/services/ARService?server=ProdLGRemV1&webService=LOG_IN_" & _
'            "Request_Tracking_BasicWS__c")> _
'        Public ReadOnly Property ADAdminConsole_Request_LOG_IN_Request_Tracking_BasicWS__cService() As String
'            Get
'                Return CType(Me("ADAdminConsole_Request_LOG_IN_Request_Tracking_BasicWS__cService"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.131.120.224;Initial Catalog=HR_MIS_STAGING;Integrated Security=Tru" & _
'            "e")> _
'        Public ReadOnly Property HR_MIS_STAGINGConnectionString() As String
'            Get
'                Return CType(Me("HR_MIS_STAGINGConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://prodlgremv1/arsys/services/ARService?server=ProdLGRemV1&webService=LOG_DM_" & _
'            "Department_BasicWS__c")> _
'        Public ReadOnly Property ADAdminConsole_LOG_DM_Department_BasicWS__c_LOG_DM_Department_BasicWS__cService() As String
'            Get
'                Return CType(Me("ADAdminConsole_LOG_DM_Department_BasicWS__c_LOG_DM_Department_BasicWS__cService"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.210\MSSQLSERVER2008;Initial Catalog=VIP_EXPANDED;User ID=sa" & _
'            ";Password=S@P@SSW0RD")> _
'        Public ReadOnly Property VIP_EXPANDEDConnectionString2008QA() As String
'            Get
'                Return CType(Me("VIP_EXPANDEDConnectionString2008QA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("")> _
'        Public Property VulindlelaUser() As String
'            Get
'                Return CType(Me("VulindlelaUser"), String)
'            End Get
'            Set(value As String)
'                Me("VulindlelaUser") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("")> _
'        Public Property ProxyOveride() As String
'            Get
'                Return CType(Me("ProxyOveride"), String)
'            End Get
'            Set(value As String)
'                Me("ProxyOveride") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("True")> _
'        Public Property Close_Pick_Forms() As Boolean
'            Get
'                Return CType(Me("Close_Pick_Forms"), Boolean)
'            End Get
'            Set(value As Boolean)
'                Me("Close_Pick_Forms") = value
'            End Set
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.210\MSSQLSERVER2008;Initial Catalog=ADS;Persist Security In" & _
'            "fo=True;User ID=sa;Password=S@P@SSW0RD")> _
'        Public ReadOnly Property ADSConnectionString1() As String
'            Get
'                Return CType(Me("ADSConnectionString1"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl), _
'         Global.System.Configuration.DefaultSettingValueAttribute("http://devlgremv1/arsys/services/ARService?server=devLGRemV1&webService=LOG_DM_Cu" & _
'            "stomer_Information_BasicWS__c")> _
'        Public ReadOnly Property ADAdminConsole_devlgremv1_LOG_DM_Customer_Information_BasicWS__cService() As String
'            Get
'                Return CType(Me("ADAdminConsole_devlgremv1_LOG_DM_Customer_Information_BasicWS__cService"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("devlgremv1")> _
'        Public Property ARSServerDevelopment() As String
'            Get
'                Return CType(Me("ARSServerDevelopment"), String)
'            End Get
'            Set(value As String)
'                Me("ARSServerDevelopment") = value
'            End Set
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute(" Data Source=10.123.45.210;Initial Catalog=VIP_EXPANDED;User ID=sa;Password=S@P@S" & _
'            "SW0RD;Connect Timeout=120")> _
'        Public ReadOnly Property VIP_EXPANDEDConnectionStringQA() As String
'            Get
'                Return CType(Me("VIP_EXPANDEDConnectionStringQA"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.210;Initial Catalog=ADS;Persist Security Info=True;User ID=" & _
'            "sa;Password=S@P@SSW0RD;Connect Timeout=120")> _
'        Public ReadOnly Property AdsQAConnectionString() As String
'            Get
'                Return CType(Me("AdsQAConnectionString"), String)
'            End Get
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.180\MSSQLSERVER2008;Initial Catalog=ADS;Persist Security In" & _
'            "fo=True;User ID=sa;Password=S@P@SSW0RD")> _
'        Public Property ADSConnectionString2008PRD() As String
'            Get
'                Return CType(Me("ADSConnectionString2008PRD"), String)
'            End Get
'            Set(value As String)
'                Me("ADSConnectionString2008PRD") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.123.45.180\MSSQLSERVER2008;Initial Catalog=VIP_EXPANDED;User ID=sa" & _
'            ";Password=S@P@SSW0RD")> _
'        Public Property VIP_EXPANDEDConnectionString2008PRD() As String
'            Get
'                Return CType(Me("VIP_EXPANDEDConnectionString2008PRD"), String)
'            End Get
'            Set(value As String)
'                Me("VIP_EXPANDEDConnectionString2008PRD") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=prodlgsqlv1.logis.gov.za\SQL2012;Initial Catalog=ARSystem;Integrated " & _
'            "Security=True;Connect Timeout=120")> _
'        Public Property ARSystemProdConnectionString() As String
'            Get
'                Return CType(Me("ARSystemProdConnectionString"), String)
'            End Get
'            Set(value As String)
'                Me("ARSystemProdConnectionString") = value
'            End Set
'        End Property

'        <Global.System.Configuration.UserScopedSettingAttribute(), _
'         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=Devlgsqlv1.logis.gov.za\SQL2012;Initial Catalog=ARSystem;Integrated S" & _
'            "ecurity=True;Connect Timeout=120")> _
'        Public Property ARSystemDevConnectionString() As String
'            Get
'                Return CType(Me("ARSystemDevConnectionString"), String)
'            End Get
'            Set(value As String)
'                Me("ARSystemDevConnectionString") = value
'            End Set
'        End Property
'    End Class
'End Namespace

'Namespace My

'    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(), _
'     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
'     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
'    Friend Module MySettingsProperty

'        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
'        Friend ReadOnly Property Settings() As Global.ADAdminDotNet.My.MySettings
'            Get
'                Return Global.ADAdminDotNet.My.MySettings.Default
'            End Get
'        End Property
'    End Module
'End Namespace
